services:
   redis:
     image: redislabs/redismod
     container_name: redis
     ports:
       - '6378:6379'
   track-trace-api:
        build: .
        container_name: flask
        env_file:
          - .env
        ports:
            - "5001:5000"
        volumes:
            - .:/code
        depends_on:
            - redis